### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by lixiang810** [88250/starfire#2]
系统环境：Archlinux，有自配dnsmasq、v2raya，但尝试关闭后问题仍未解决。  
网络环境：广东广电网络/广东电信/美国洛杉矶，均无法ping通47.111.58.76。  
全程按readme.md里进行操作，使用pacman -S go-ipfs进行ipfs的安装，同样尝试过docker，然而docker在`sudo docker exec ipfs_host ipfs bootstrap rm --all`时直接报错`Error: No such container: ipfs_host`。
使用pacman安装的ipfs可以正常进行后续操作，然而在运行完命令后，浏览器（Chromium）却无法访问[http://127.0.0.1:8080/ipfs/QmauDX9WwBwVscpyXkHhxDr3AtDTLwHqjQ5MnJNEjWekMw](http://127.0.0.1:8080/ipfs/QmauDX9WwBwVscpyXkHhxDr3AtDTLwHqjQ5MnJNEjWekMw)。一直显示“正在等待127.0.0.1的响应”。奇怪的是，当我对ipfs Ctrl+C以后，页面倒能加载出来一条`ipfs cat /ipfs/QmauDX9WwBwVscpyXkHhxDr3AtDTLwHqjQ5MnJNEjWekMw: promise channel was closed`
```
Initializing daemon...
go-ipfs version: 0.5.1-8431e2e87
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: 67c935b8ed72b6a530e34a16cf5167a8
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/192.168.252.1/tcp/4001
Swarm listening on /ip4/192.168.88.100/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.1/tcp/4001
Swarm announcing /ip4/192.168.252.1/tcp/4001
Swarm announcing /ip4/192.168.88.100/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```
嗯同时也无法访问[http://127.0.0.1:5001/webui](http://127.0.0.1:5001/webui)，可能是ipfs的问题，然而我并不懂ipfs，所以还是开了这个issue。

**Comment by 88250** [comment]
星火网络只有一个主节点，目前处于关闭状态，等到以后有机会再重启，希望届时会有其他人一起搭建主节点群，谢谢。

**Comment by lixiang810** [comment]
emmmmmm那么我被允许拿这些代码自架吗？
LICENSE是什么？

**Comment by 88250** [comment]
没问题的，随意折腾。
