### ISSUE TITLE
您好，我现在也在做类似星火项目的一个社区系统

### ISSUE THREAD

**Issue by 42cake** [88250/starfire#5]
上次问过您这个项目是否在做了，您的回答我收到了，我目前也在做一个类似的系统，是区块链＋ipfs的社区，有一些思路跟您的星火项目有些部分是相似的，但是就ipfs个人用户数据储存我们利用pinata和nft.storage类似的平台去做，的但是我想您做过这个项目所以想请教一些问题，我很认同‘数据及权利’
像这个项目里类似星火管理员中心化的问题我有一些很棒的主意，我想和您沟通一下，请教一些问题交流一下想法，我加您qq了但是您没有同意，麻烦请问可以同意一下么？

**Comment by 88250** [comment]
你好，我的 QQ 可能是因为加人太多，已经收不到通知了，有问题请直接在这里讨论，谢谢。

**Comment by 42cake** [comment]
好的，我注意到您的链滴社区支持eth钱包登录，这个主意非常的棒，但是我不太清楚您的钱包登录是如何运作的？是地址绑定相关用户信息还是？，我是想做类似只用钱包当作唯一用户识别系统，（https://github.com/amaurym/login-with-metamask-demo）
然后结合ipfs做数据储存，不知道您是否有关注过btfs（https://docs.btfs.io/docs/btfs-gateway-user-guide）但是btfs的网关目前好像对大陆地区用户不太行。所以我们ipfs使用（pinata.cloud）这个系统，他们的网关和引脚管理比较好，但是每个用户免费使用空间1GB，个人写写博客还是不错的。您应该也对区块链有过了解，我也是开源的自由工作者，目前在做X-DAO组织，我注意到很多区块链论坛还是用传统用户登录方式，细分领域很多公链没有很好的论坛系统，所以有了这个想法，目前进度卡了，刚开始是参考开源项目（https://github.com/songboriceman/doubao_community_backend）做的，现在就引入钱包登录以及ipfs数据管理有点不太行。。非常感谢您的回答，谢谢！

**Comment by 42cake** [comment]
好的，我注意到您的链滴社区登录，这个大规模支持的棒，但我不太清楚您的登录是如何支持的？
是地址绑定用户信息还是？，我是确认类似只用钱包当作唯一用户识别系统[](https://github.com/amaurym/login-with-metamask-demo)
然后结合ipfs做数据存储，不知道您是否有关注过btfs[](https://github.com/amaurym/login-with-metamask-demo) docs.btfs.io/docs/btfs-gateway-user-guide）
但是btfs的网关目前好像对大陆用户地区不太行。所以我们ipfs使用[](pinata.cloud)这个系统，他们的网关和权限管理比较好，但是每个人都免费免费空间1GB，个人写博客还是不错的。
继续用连续用户登录方式，论坛领域很多公链没有这个论坛系统，所以有了新的思路，现在块卡了，刚开始是参考开源项目[](https://github.com/songboriceman /doubao_community_backend)做的，现在就输入数据下载和ipfs管理有点不太行。。非常感谢你的回答，谢谢！

**Comment by 42cake** [comment]
好的，我注意到您的链滴社区登录，是支持eth钱包登陆的我认为非常的棒，但我不太清楚您的登录是如何支持的？
是钱包地址绑定用户信息还是？我目前思路是用钱包用户签名作唯一用户识别
[](https://github.com/amaurym/login-with-metamask-demo)
然后结合ipfs做数据存储，不知道您是否有关注过btfs
[](docs.btfs.io/docs/btfs-gateway-user-guide)
但是btfs的网关目前好像对大陆地区不太行。
所以我们ipfs使用[](pinata.cloud)这个系统
他们的网关和引脚管理比较好
1GB空间的话个人写博客还是不错的。
您应该是对区块链领域是有所关注的，我注意到很多公链没有论坛系统以及链下投票链上合约支持
目前类似的项目[](https://github.com/snapshot-labs/snapshot)，
本人也是开源爱好者，我们在做DAO组织，目前主链是TRX
不过我目前是在做类似社区框架和您的星火项目有些思路是相似的
刚开始是参考开源项目[](https://github.com/songboriceman /doubao_community_backend)做的
现在就钱包用户认证以及ipfs管理有点不太行。。
非常感谢你的回答，谢谢！

**Comment by 88250** [comment]
> 是钱包地址绑定用户信息还是？我目前思路是用钱包用户签名作唯一用户识

是的，用户设置钱包地址。

**Comment by 42cake** [comment]
emmm不知道是不是因为google翻译的问题，有些东西消失了。。
我现在参考的方案有如下
用户认证：[https://github.com/amaurym/login-with-metamask-demo](url)
ipfs：第三方引脚管理以及网关[pinata.cloud](url)
以及DAO治理社区参考：[https://github.com/snapshot-labs/snapshot](url)

**Comment by 42cake** [comment]
> > 是钱包地址绑定用户信息还是我现在的想法是用钱包用户签名作唯一用户识
> 
> 是的，用户设置钱包地址。

是服务器用户id绑定钱包地址么？emmm应该说是用地址实现登录？

**Comment by 88250** [comment]
是的，用户自己设置钱包地址，后端关联到 user id 上。

**Comment by 42cake** [comment]
> 是的，用户自己设置钱包地址，后端关联到 user id 上。

请问那星火项目还会继续么？

**Comment by 88250** [comment]
以后有机会的话会继续的，目前主要在做 https://github.com/siyuan-note/siyuan 欢迎关注 :)

**Comment by 42cake** [comment]
好的
非常感谢您的回复

**Comment by 88250** [comment]
我关闭了，如果需要交流请随时更贴，谢谢。
